### ISSUE TITLE
task1

### ISSUE THREAD

**Issue by ksilobait** [MihaNiZZm/os_labs_5th_semester#1]
## 1.1
Нужно использовать табуляцию одного типа и не смешивать пробелы и tab символы в одном файле - число проблелов в одном tab символе (2, 4 или 8) настроено по-разному в разных местах
![image](https://github.com/MihaNiZZm/os_labs_5th_semester/assets/17474821/ea7f15e6-aabc-4c01-affb-9317f437724b)
![image](https://github.com/MihaNiZZm/os_labs_5th_semester/assets/17474821/482f3777-7fa9-4361-8dff-c55f6a8d6618)

На каждое выделение памяти (`malloc`) должно быть освобождение (`free`)

## 1.2
У всех системных вызовов (в том числе `pthread_detach`) нужно проверять возвращаемое значение

## 1.3
`malloc` - системный вызов, и может по многим причинам неуспешно завершиться, нужно проверять этот случай в коде

## 1.4
`pthread_testcancel` не нужно вызывать при наличии рядом `printf`, внутри которого уже заложена точка отмены

## 1.5
`signal` - устаревший метод, и нужно использовать `sigaction`, только если нет серьезных причин использовать `signal`

## 1.6
У меня и на сервере код не работает - цикл `mythread_join` бесконечно исполняется, не выходя по условию `exited`

**Comment by ksilobait** [comment]
## 1.1
Форматирвоание не исправлено
![image](https://github.com/MihaNiZZm/os_labs_5th_semester/assets/17474821/c95ff47f-1201-4d71-9e2b-2bc39dfed261)

В b.c (и следующих файлах) не освобождается память при ошибке pthread_create

Нет проверки, что malloc корректно выделил память

## 1.6
В `child_function` у `args` и в `mythread_join` у `thread` разные адреса, mythread_join не видит изменения проводимые в это время операциями `args->retval = ` и `args->exited = `
Пока не могу быстро найти причину

У конструкции while разное форматирование в 14 и 81 строках

**Comment by MihaNiZZm** [comment]
Здравствуйте! Пофиксил и залил все правки.

пт, 17 нояб. 2023 г. в 20:53, Ruslan Izhitsky ***@***.***>:

**Comment by ksilobait** [comment]
## 1.6
clone как и close устанавливает errno, но у clone для вывода ошибки используется printf

Нет проверки работы mprotect, ftruncate, mmap

**Comment by MihaNiZZm** [comment]
Fixed.

ср, 22 нояб. 2023 г. в 23:40, Ruslan Izhitsky ***@***.***>:
