### ISSUE TITLE
task3

### ISSUE THREAD

**Issue by ksilobait** [MihaNiZZm/os_labs_5th_semester#2]
В консоли может отображаться много мусора
![image](https://github.com/MihaNiZZm/os_labs_5th_semester/assets/17474821/73ecd6bf-71ee-421a-a6c7-52f0a1beb80f)

zsh: segmentation fault (core dumped) при использовании telnet (и так же при вводе мусора)
![image](https://github.com/MihaNiZZm/os_labs_5th_semester/assets/17474821/92403680-9644-4262-86ab-65e3698f7e43)
![image](https://github.com/MihaNiZZm/os_labs_5th_semester/assets/17474821/20e93b6b-db15-418f-a586-dbd49ee51692)

**Comment by MihaNiZZm** [comment]
Done.

вт, 26 дек. 2023 г. в 21:47, Ruslan Izhitsky ***@***.***>:
